### ISSUE TITLE
not able to run the code 

### ISSUE THREAD

**Issue by chetan130297** [JavaPOSWorkingGroup/javapos#7]
hello i am not abel to run the code . i followed the instruction on this page :- https://sourceforge.net/p/javapospostest2/wiki/Import%20POSTest2%20into%20your%20IDE/

**Comment by kuniss** [comment]
@chetan130297, _JavaPOS_ and  _JavaPOS POSTest_ are not the same and maintained by different people!

JavaPOS is a library, more a framework, for implementing standardized access to retail peripherals.

_JavaPOS POSTest_ is an application which allows to test the implementation of such an access to a retail peripheral. It uses the _JavaPOS_ library as any JavaPOS application would use it.

In case you have problems to get the _JavaPOS POSTest_ application running, please reach out to people which are maintaining _POSTest_. 

I'm going to close this issue because it is not related to the _JavaPOS_ library itself.
